# first stage
FROM python:3.8 AS builder
COPY python/requirements.txt .

# install dependencies to the local user directory (eg. /root/.local)
RUN pip install --user -r requirements.txt

# second unnamed stage
FROM python:3.8-slim
WORKDIR /code

# copy only the dependencies installation from the 1st stage image
COPY --from=builder /root/.local /root/.local
COPY ./python/src .
COPY ./python/credentials/twitter_credentials.json .

# update PATH environment variable
ENV PATH=/root/.local:$PATH

CMD [ "python", "./twitter_collector.py" ] 
